# Generated by Django 4.2.8 on 2023-12-23 15:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollegeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_name", models.CharField(max_length=255)),
                ("course_offered", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=15)),
                ("district", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="ImageInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("photo_upload", models.ImageField(upload_to="covers/")),
            ],
        ),
        migrations.CreateModel(
            name="UserInformation",
            fields=[
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("region", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("coursename", models.CharField(max_length=255)),
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_form.collegeinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=15)),
                ("previous_college_name", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pass", "Pass"),
                            ("Fail", "Fail"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_form.userinformation",
                    ),
                ),
            ],
        ),
    ]
