# Generated by Django 4.2.8 on 2023-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_form", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vegetables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="cover",
            field=models.ImageField(upload_to="covers/"),
        ),
    ]
