# Generated by Django 4.2.8 on 2023-12-23 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.IntegerField(
                        help_text="Enter your phone number",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]*$",
                                message="Phone number must contain only digits",
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField()),
            ],
        ),
    ]
